apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: hw12-ns
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
          - containerPort: 80
 
---
# NodePod service example

apiVersion: v1
kind: Service
metadata:
  name: nodeport
  namespace: hw12-ns
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
  
---

# ClusterIp service example

apiVersion: v1
kind: Service
metadata:
 name: myservice-clusterip
 namespace: hw12-ns
spec:
  clusterIP: 10.96.1.10
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80 
  selector:
    app: nginx
  type: ClusterIP   
